# Generated by Django 6.1 on 2026-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public repo koi bhi padh sakta hai. Private sirf owner aur organisation members ko dikhta hai.'),
        ),
    ]
