# Generated by Django 6.1 on 2026-09-15 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0002_repository_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], default='file', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.filenode')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_nodes', to='repositories.repository')),
            ],
            options={
                'ordering': ['-node_type', 'name'],
                'indexes': [models.Index(fields=['repository', 'parent'], name='files_filen_reposit_cbebe8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('repository', 'parent', 'name'), name='unique_node_name_in_folder'), models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('repository', 'name'), name='unique_node_name_at_root')],
            },
        ),
    ]
